apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-postgresql-pvc
spec:
  accessModes:
    - {{ .Values.postgresql.persistence.accessModes | join ", " }}
  resources:
    requests:
      storage: {{ .Values.postgresql.persistence.size }}